// src/lib/verantwoording.ts
// [VERANTWOORDING] The one page the accountant can put in his client file and show to someone else.
// Run: npx tsx --test src/lib/verantwoording.test.ts
//
// ── WHY A PDF, WHEN THE ZIP ALREADY CONTAINS EVERYTHING ──
//
// The quarter package holds the facts: the documents, the statement, the reconciliation, the raw
// BTW figures and every gap we could not close. All of it is complete and none of it is SHOWABLE.
// A CSV is a working file; a folder of PDFs is evidence. Neither is a page a professional puts in
// front of a third party — his client, his own reviewer, or the Belastingdienst at a boekencontrole
// — to say what was delivered, on what date, and what was established from it.
//
// So this is not new information. It is the same numbers on a page that can be printed, filed and
// handed over, generated by the same renderer as the invoice PDF so it carries a real text layer.
//
// ── AND THE LINE IT MUST NOT CROSS ──
//
// This is NOT an accountantsverklaring and not a samenstellingsverklaring. Those are regulated
// statements made by a person who takes responsibility for them, and a document that merely LOOKS
// like one is worse than no document at all: it would put a claim in an accountant's file that he
// never made, about work he has not yet done. So the page says, in its own words, that it is a
// hand-over by software, that nothing here is a filed aangifte, and that the assessment is his.
//
// ── WHY IT CARRIES THE BAD NEWS TOO ──
//
// Every warning goes on it, in full. A cover sheet with only good news on it is precisely the kind
// of document that becomes a liability — it is the page somebody quotes later, and what it left out
// is the part he will be asked about. The gaps are on the same page as the counts, in the same
// type, under a heading that says what they are.
//
// Dutch, like every other document in the package.

import type { ClosingPackageWarning } from "./closing-package";
import type { HandoverTotals } from "./bank-handover";
import type { ContinuityReport, SeriesReport } from "./invoice-continuity";

/** One BTW rate's turnover, as buildQuarterlySummary reports it. */
export type VerantwoordingRate = { rate: number; totalExcl: number; totalBtw: number };

/** Everything the page states. Assembled by the package; rendered by verantwoording-pdf.tsx. */
export type Verantwoording = {
  quarterLabel: string;
  clientName: string;
  /** The owner's own identifiers, when they are known. Absent is absent — never an empty string. */
  kvkNumber: string | null;
  btwNumber: string | null;
  /** ISO. The page prints the date, because "when was this handed over" is half of what it proves. */
  generatedAt: string;

  outgoingCount: number;
  incomingCount: number;
  filesIncluded: number;
  eInvoiceCount: number;
  bankStatementIncluded: boolean;

  /** RAW sales turnover per rate. Never a vat_due — see the header of closing-package.ts. */
  salesByRate: VerantwoordingRate[];
  totalSalesIncl: number;
  totalPurchaseIncl: number;
  btwOnSales: number;
  btwOnPurchases: number;

  /** null when there was nothing to reconcile, or when the bank could not be read. */
  handover: HandoverTotals | null;
  /**
   * [DOORLOPEND] De doorlopende nummerreeks (art. 35 Wet OB), of null wanneer de nummers niet
   * gelezen konden worden.
   *
   * Dit staat op de pagina óók als er niets mis is, en dat is met opzet: het is het eerste dat een
   * boekhouder nakijkt, en een controle die alleen spreekt als ze iets vindt bewijst niet dat ze
   * gedraaid heeft. "Gecontroleerd en in orde, van 20260001 tot 20260046" is precies de zin waar
   * deze pagina voor bestaat.
   */
  numbering: { report: ContinuityReport; countersRead: boolean } | null;
  /**
   * [DEKKING] One sentence about a quarter whose statements do not cover it, or null.
   *
   * It stands INSIDE the reconciliation section and above its numbers, for the same reason it
   * does in bankafletering.csv: it changes what those numbers mean. It is also repeated among the
   * warnings below — deliberately. This is the page somebody quotes, and the reader who quotes
   * the reconciliation must have read the qualification in the same breath, not four lines lower
   * under a different heading.
   */
  coverage?: string | null;
  warnings: ClosingPackageWarning[];
};

// [VERANTWOORDING] Hier stond een buildVerantwoording(args) die `args` teruggaf. Een functie die
// niets doet, en die daardoor de indruk wekt dat er ergens iets wordt samengesteld dat gecontroleerd
// kan worden. Het TYPE is de afspraak; het samenstellen gebeurt in closing-package.ts waar de
// getallen definitief zijn. Weg.


/**
 * The sentence about the reconciliation, or null when there is nothing to say.
 *
 * Its own function because it is the claim most likely to be quoted, and the one where a plural, a
 * zero or a missing "nog open" changes what was promised. Null when the bank could not be read:
 * silence is correct there, and "0 van 0 gekoppeld" is not.
 */
export function handoverSentence(h: HandoverTotals | null): string | null {
  if (!h || h.lines === 0) return null;
  const matched = `${h.matched} van de ${h.lines} bankregels ${h.matched === 1 ? "is" : "zijn"} aan een factuur gekoppeld`;
  if (h.unmatched === 0) return `${matched}; er staat geen regel meer open.`;
  return `${matched}; ${h.unmatched === 1 ? "één regel staat" : `${h.unmatched} regels staan`} nog open.`;
}


/**
 * De nummerreeks in zinnen, één per reeks, plus het oordeel.
 *
 * Puur en apart, omdat dit de tekst is die een derde leest en het rekenwerk niet. `countersRead`
 * hoort er zichtbaar bij: zonder de tellers is alleen het MIDDEN van de reeks nagekeken, en het
 * einde is precies waar een verbrand nummer het vaakst zit. Een halve controle die zich als hele
 * presenteert is hier de duurste fout die er is.
 */
export function numberingLines(n: { report: ContinuityReport; countersRead: boolean } | null): {
  lines: string[];
  verdict: string;
} {
  if (!n) {
    return { lines: [], verdict: "De factuurnummering kon niet worden nagekeken." };
  }
  const name = (s: SeriesReport) =>
    `${s.type === "creditnota" ? "Creditnota's" : "Facturen"}${s.year === null ? "" : ` ${s.year}`}`;

  const lines = n.report.series.map((s) => {
    const range = `${s.first} t/m ${s.last}`;
    const bits: string[] = [`${name(s)}: ${range}, ${s.issued} ${s.issued === 1 ? "stuk" : "stuks"}`];
    if (s.missing.length > 0) {
      bits.push(`${s.missing.length === 1 ? "nummer" : "nummers"} ${s.missing.slice(0, 10).join(", ")}${s.missing.length > 10 ? " en meer" : ""} nooit uitgereikt`);
    }
    if ((s.burnedAtEnd ?? 0) > 0) bits.push(`teller staat ${s.burnedAtEnd} hoger dan de laatste factuur`);
    if (s.duplicates.length > 0) bits.push(`dubbel: ${s.duplicates.join(", ")}`);
    if (s.missing.length === 0 && (s.burnedAtEnd ?? 0) === 0 && s.duplicates.length === 0) bits.push("doorlopend");
    return bits.join(" — ");
  });

  if (n.report.unreadable.length > 0) {
    lines.push(
      `Niet te plaatsen in een bekend formaat: ${n.report.unreadable.slice(0, 8).join(", ")}${n.report.unreadable.length > 8 ? " en meer" : ""}.`,
    );
  }

  if (n.report.series.length === 0 && n.report.unreadable.length === 0) {
    return { lines: [], verdict: "Er zijn nog geen genummerde facturen." };
  }

  const verdict = n.report.clean
    ? n.countersRead
      ? "Gecontroleerd: de nummering loopt door, zonder gaten."
      : "Gecontroleerd voor zover mogelijk: er zitten geen gaten tussen de uitgereikte nummers. Het einde van de reeks konden we nu niet nakijken."
    : "Er zit een onderbreking in de nummering. Een verbrand nummer kun je niet opnieuw gebruiken; het gaat erom dat het verklaard is.";
  return { lines, verdict };
}
