// scripts/context-integrity.mts
// [SAMENHANG] Turn the integrity catalogue into one SQL script, the way migration-inventory.ts
// turns the migrations folder into one.
//
//   npx tsx scripts/context-integrity.mts                 → the SQL, on stdout
//   npx tsx scripts/context-integrity.mts | psql "$DATABASE_URL"
//
// ── WHY A GENERATOR AND NOT A CLIENT ────────────────────────────────────────────────────────
//
// The same reason migration-inventory.ts is one: a hand-maintained list ABOUT a hand-maintained
// list does not get anywhere. The checks live in src/lib/context/integrity.ts, where a unit test
// can demand that each of them is read-only, single-valued, paired with a population count and
// accompanied by a reason. This file only arranges them.
//
// It also means the tool needs no credentials and no network to be useful. A generator cannot leak
// a service-role key, cannot write to production by accident, and runs on a clean checkout — which
// is what makes it something a person will actually run.
//
// ── HOW TO READ THE OUTPUT ──────────────────────────────────────────────────────────────────
//
// One row per check: id, what it counts, the number, and a verdict. The verdict is not simply
// "n = 0": a violation check is reported as UNPROVEN rather than OK when the population it depends
// on is below its floor, because zero out of nothing is not a result. verify-tenant-isolation.mts
// puts it exactly right — "hiding 595 invoices is a result; hiding none is a sentence with no
// subject".

import { INTEGRITY_CHECKS } from "@/lib/context/integrity";

const lines: string[] = [];

lines.push("-- [SAMENHANG] Relationship integrity — GENERATED by scripts/context-integrity.mts.");
lines.push("-- Do not edit here: edit src/lib/context/integrity.ts and regenerate.");
lines.push("-- Read-only. Every statement below is a SELECT; nothing in this file can change a row.");
lines.push("");
lines.push("WITH");

const parts: string[] = [];
for (const c of INTEGRITY_CHECKS) {
  // Each check becomes its own CTE, so one round trip answers all of them and a slow check cannot
  // silently be skipped by somebody running half the file.
  parts.push(`  ${cteName(c.id)} AS (${c.sql})`);
}
lines.push(parts.join(",\n"));

const selects: string[] = [];
for (const c of INTEGRITY_CHECKS) {
  const pop = c.expect === "zero"
    ? `(SELECT n FROM ${cteName(c.believableBecause)})`
    : "NULL::bigint";
  const floor = c.expect === "zero"
    ? String(INTEGRITY_CHECKS.find((x) => x.id === c.believableBecause)?.floor ?? 0)
    : String(c.floor);
  const verdict = c.expect === "population"
    ? `CASE WHEN n >= ${c.floor} THEN 'OK' ELSE 'TOO THIN — a zero here would prove nothing' END`
    : `CASE WHEN ${pop} < ${floor} THEN 'UNPROVEN — population below floor' ` +
      `WHEN n = 0 THEN 'OK' ELSE 'FINDING' END`;
  selects.push(
    // `check` is a RESERVED WORD in Postgres, so it cannot be an unquoted output name — an
    // ORDER BY on it fails with 42601 at the very end of the script, after every CTE has already
    // run. Found by running the generated SQL rather than by reading it.
    `SELECT ${sqlStr(c.id)} AS check_id, ${sqlStr(c.family)} AS family, ` +
    `${sqlStr(c.expect)} AS kind, n::text AS n, ${verdict} AS verdict, ${sqlStr(c.title)} AS title ` +
    `FROM ${cteName(c.id)}`,
  );
}

lines.push(selects.join("\nUNION ALL\n") + "\nORDER BY kind DESC, check_id;");
lines.push("");

process.stdout.write(lines.join("\n"));

function cteName(id: string): string {
  return "c_" + id.replace(/[^a-z0-9]+/gi, "_").toLowerCase();
}

function sqlStr(v: string): string {
  return "'" + v.replace(/'/g, "''") + "'";
}
